name: Nightly Release Branch
on:
  # Run daily at 2:30am UTC
  schedule:
    - cron: '30 2 * * 1-5'
jobs:
  increment-version:
    # prevents this action from running on forks
    if: github.repository_owner == 'facebook'
    uses: ./.github/workflows/call-increment-version.yml
    with:
      channel: nightly
      increment: prerelease
      dry-run: false
      git-repo: 'git@github.com:facebook/lexical.git'
    secrets:
      SSH_KEY_2: ${{ secrets.SSH_KEY_2 }}
  npm-release:
    uses: ./.github/workflows/call-npm-publish.yml
    needs: [increment-version]
    with:
      ref: ${{ needs.increment-version.outputs.tag-ref }}
      dry-run: false
      channel: nightly
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
